### ISSUE TITLE
Just a detail

### ISSUE THREAD

**Issue by turiot** [mcheung63/MavenRunner#1]
Thanks a lot for this plugin !

Just a detail, the output window's title is 'Peter-swing library', not the common 'Build(<project>)'.

**Comment by mcheung63** [comment]
Thanks, i fixed it today. Please pull the latest source :-)

**Comment by markiewb** [comment]
{quote}
Thanks, i fixed it today. Please pull the latest source :-)
{quote} 
So this issue can be closed?
