### ISSUE TITLE
UI should be updated, when new projects are opened/actual project are getting closed

### ISSUE THREAD

**Issue by markiewb** [mcheung63/MavenRunner#10]
See http://wiki.netbeans.org/DevFaqListenForOpeningClosingProject

**Comment by markiewb** [comment]
@mcheung63: In your commits please include the issue number! https://github.com/mcheung63/MavenRunner/commit/1dc70ee484e4435c900d9ed9e3e87862ea9c961c

This way the issue and commits are connected. Github will show all commits which match the current issue, which is quite convient. F.e. ```Fix NPE #10```

**Comment by mcheung63** [comment]
thanks for telling :-)

Thanks
From Peter

**Comment by mcheung63** [comment]
Fixed, but i found something weird in netbeans plugins programming

1) I have a root tree node decleared in class, but it has to be static, other it will be changed.
2) tree.getModel != my model
