### ISSUE TITLE
Add context menu entry to start the goal

### ISSUE THREAD

**Issue by Chris2011** [mcheung63/MavenRunner#12]
I know that I can start the custom goal via double clicking, but it would be better if we can have a context menu entry, when I right click on the goal to "Execute goal" or smth like that. There is no way to know how to execute the goal instead, except try it out.

Regards

Chris

**Comment by mcheung63** [comment]
thanks, adding the menu now.

**Comment by mcheung63** [comment]
Fixed, added menu to run goal, please download the latest nbm
