### ISSUE TITLE
Provide a signed version for the plugin center

### ISSUE THREAD

**Issue by markiewb** [mcheung63/MavenRunner#15]
Only this way your plugin can be downloaded directly from the IDE.

**Comment by mcheung63** [comment]
thanks, just uploaded the signed nbm, please try http://plugins.netbeans.org/plugin/60381/?show=true

**Comment by markiewb** [comment]
Your plugin is not correctly signed. If it is signed, then you can request a verification to be in the pool of the plugins in the update center.

![2016-02-27_16h03_47](https://cloud.githubusercontent.com/assets/1857095/13379180/3ed4f71a-de1f-11e5-9786-81d93c837330.png)


http://wiki.netbeans.org/FaqPluginRequirements
http://wiki.netbeans.org/DevFaqSignNbm

**Comment by mcheung63** [comment]
Thanks Mike, i uploaded a new nbm and click "request verification", now it is "verification PENDING". thanks

**Comment by markiewb** [comment]
That's better. In some days your plugin will now available for all the NB users. 

Even better: Once they installed your plugin and you provide a new version of the plugin (using the same verification process) the new version will be provided to all these users as an update.

**Comment by mcheung63** [comment]
thanks Mr Markiewb, you helped me a lot to get into netbeans plugins development. Thanks so much !

**Comment by markiewb** [comment]
@mcheung63: You are welcome!
