### ISSUE TITLE
NPE while running goal

### ISSUE THREAD

**Issue by Chris2011** [mcheung63/MavenRunner#16]
Atm, I don't know what I did but instantely I got an NullPointerException after while executing a goal via the MavenRunner:

```
java.lang.NullPointerException
	at org.netbeans.modules.maven.execute.BeanRunConfig.getMavenProject(BeanRunConfig.java:168)
	at org.netbeans.modules.maven.execute.MavenCommandLineExecutor$1.taskFinished(MavenCommandLineExecutor.java:161)
	at org.openide.util.Task.notifyFinished(Task.java:240)
	at org.netbeans.core.execution.ExecutorTaskImpl.finished(ExecutorTaskImpl.java:89)
[catch] at org.netbeans.core.execution.RunClassThread.run(RunClassThread.java:175)
```

the output window opens but it is empty. If you need more info, I will check what exactly the problem is.

Cheers

Chris

**Comment by mcheung63** [comment]
Thanks Chris, let me check it.

**Comment by Chris2011** [comment]
Anything new here? Can't use the plugin anymore :(

**Comment by mcheung63** [comment]
i believe the netbeans api is not stable, sometime i click on the goal but nothing happen, i just close the MavenRunner window and open it again, everything back to work.

**Comment by Chris2011** [comment]
Sry but this "solution" is unacceptable. In the first days of the plugin it worked fine, I don't know what happend than but it didn't worked anymore. Please debug your plugin to get rid of the error. I will check at work whether the "solution" is working or not but this is not a solution. And of course the NB API should be stable enough.

**Comment by mcheung63** [comment]
May i know what os and jdk version you are using? let me replicate the problem, thanks

**Comment by Chris2011** [comment]
Windows 10 64bit and JDK 8u72

**Comment by mcheung63** [comment]
I made a big mistake, everytime i compile a nbm and submit to netbeans plugin central and i thought it is done. I forgot to sign the nbm so the latest version havent been sync to plugin central, so you guys are always using the old version. Please try out version 3.5 after the nbm is verified

http://forums.netbeans.org/viewtopic.php?t=66213
http://plugins.netbeans.org/plugin/60381/?show=true

**Comment by Chris2011** [comment]
I tested the 3.5 and the problem with the NPE still exists. As you said after close and reopen the window everything is fine, but this is not an option each time.
