### ISSUE TITLE
Items have background color

### ISSUE THREAD

**Issue by Chris2011** [mcheung63/MavenRunner#18]
I use the darcula laf and my items has a ligther background color than the background itselfs. I think we don't need them, they should look as every tree node item in project, files or favorites without having a background color.

here you can see what I mean:
![mavenrunnerbgcolor](https://cloud.githubusercontent.com/assets/795658/16514563/e8ab780a-3f6c-11e6-8637-4db272366de4.png)

**Comment by mcheung63** [comment]
thanks, let me fix it tomorrow

**Comment by mcheung63** [comment]
Fixed, tested these look & feel : Metal, Nimbus, Dracula, Macosx, CDE. Please try the latest version 3.3, thanks for submitting bug.
<img width="451" alt="2016-07-03 1 03 51" src="https://cloud.githubusercontent.com/assets/1779905/16543826/ada74d48-411e-11e6-8d13-50d28cce701b.png">
