### ISSUE TITLE
Shows each project which is open

### ISSUE THREAD

**Issue by Chris2011** [mcheung63/MavenRunner#2]
First, big compliment to you, nice tool, but the tool calls mavenrunner, so it should only shows maven based project and not all (For me maven based projects, netbeans java module, html5 project).

Regards

Chris

**Comment by mcheung63** [comment]
yes, you are correct, going to enhance it.

**Comment by mcheung63** [comment]
Fixed, please update to latest version, thanks

**Comment by Chris2011** [comment]
Thx, it works as expected. :)
