### ISSUE TITLE
Run Maven Goal with Properties doesn't work

### ISSUE THREAD

**Issue by mazze5** [mcheung63/MavenRunner#20]
HIi,

I use NetBeans 8.2. If I run maven goal from nbactions direct from netbeans context menu it works. But if I do the same from maven runner view it doesn't work.

I figured out that the problem only exists with nbaction with properties.
`<action>
        <actionName>CUSTOM-myaction</actionName>
        <displayName>MyAction</displayName>
        <goals>
            <goal>-U</goal>
            <goal>compile</goal>
            <goal>exec:java</goal>
        </goals>
        <properties>
            <myProperty>ABC</myProperty>
        </properties>
        <activatedProfiles>
            <activatedProfile>MyProfile</activatedProfile>
        </activatedProfiles>
    </action>`

In the output I can see that the property "myProperty" is passed like this `-D>myProperty=abc`
And I think this comes from the following line of code: https://github.com/mcheung63/MavenRunner/blob/44184760f6317887e9e553d2ced90818e8f68e10/src/com/peter/mavenrunner/MavenRunnerTopComponent.java#L746

Why do you put a ">" in front of the property?

**Comment by mcheung63** [comment]
Thanks, i am uploading a new version to plugin central, please try when it available.
