### ISSUE TITLE
Doesn't show me my custom goals which I defined before.

### ISSUE THREAD

**Issue by Chris2011** [mcheung63/MavenRunner#3]
Before I used your tool, I did this: right click on a project -> properties -> actions -> add new(custom) action. So when I do right click on a project and go to custom I see 2 goals. Now I open your mavenrunner window and see my projects but the custom goals which I defined before I had your tool, are not available. I expect, that it shouldn't matter, where I add my custom goals. In your tool or in netbeans default functionality. Each goal should be there in your tool and in the netbeans default behavior.

Regards

Chris

**Comment by mcheung63** [comment]
Thanks for using, MavenRunner manage the goals separately. Let me add code to sync with the netbeans project goals. I am new to netbeans plugin development, i still don't know which code can sync with it, let me do some research, thanks

**Comment by markiewb** [comment]
IMO there is no public API for that, but the configuration is persisted in ```nbactions.xml``` next to the pom.xml. So it possible to keep this in sync. Or your plugin could persist its configuration in the ```nbaction.xml``` file

![2016-01-03_19h35_48](https://cloud.githubusercontent.com/assets/1857095/12080128/a087e552-b251-11e5-8c52-697195f8dd67.png)

**Comment by mcheung63** [comment]
Hey markiewb , super cool for your tips, i am on the way to that.

**Comment by markiewb** [comment]
You're welcome. Once it's done, I can test it and give you feedback.

Best regards, markiewb

----- Ursprungligt meddelande -----
Från: "Peter" <notifications@github.com>
Skickat: ‎04.‎01.‎2016 17:41
Till: "mcheung63/MavenRunner" <MavenRunner@noreply.github.com>
Kopia: "markiewb" <benno.markiewicz@googlemail.com>
Ämne: Re: [MavenRunner] Doesn't show me my custom goals which I definedbefore. (#3)

Hey markiewb , super cool for your tips, i am on the way to that.

**Comment by markiewb** [comment]
@mcheung63: Any news here? Could you invest time to figure it out?

**Comment by mcheung63** [comment]
Dear Mark, i publish a new version next monday. Sorry late reply, so rush these few weeks for some projects :-(

**Comment by mcheung63** [comment]
http://peter.kingofcoders.com/?p=2002
http://plugins.netbeans.org/plugin/60381/mavenrunner

**Comment by Chris2011** [comment]
your first link, doesn't work.

**Comment by mcheung63** [comment]
sorry @Chris2011, my server is down, will back to work tuesday
