### ISSUE TITLE
Remove the font-size setting

### ISSUE THREAD

**Issue by markiewb** [mcheung63/MavenRunner#5]
![2016-02-13_10h53_48](https://cloud.githubusercontent.com/assets/1857095/13027127/4f4549a2-d243-11e5-88a3-dfa1e5dab184.png)

Why this feature? What's wrong with the standard size? Else the UI of that TopComponents would look different to the other UI. Even the TreeRenderer does not care about the size

**Comment by mcheung63** [comment]
Because in my 27" 5k iMac, the font is very very small, because i am frequently click on maven runner, so i want to let people to have bigger font size.

**Comment by markiewb** [comment]
I will provide a pull request, which moves this setting to an option panel

**Comment by markiewb** [comment]
@mcheung63: 

a) Use a different laf, which allows you to set the overall font-size. For example

https://blogs.oracle.com/geertjan/resource/darcula-laf-4-nbp-2.png
http://plugins.netbeans.org/plugin/62424/darcula-laf-for-netbeans

OR
b) set the font-size for the LAF via cmdline-options 
http://wiki.netbeans.org/FaqFontSize

**Comment by mcheung63** [comment]
thanks

**Comment by Chris2011** [comment]
What happens to this ticket? The font option is still there.

**Comment by Chris2011** [comment]
Any problems to fix it?

**Comment by mcheung63** [comment]
lets respect democracy, i removed the font size buttons since people doesn't want it. It is available in version 3.3
