### ISSUE TITLE
TreeRenderer uses hard-coded colors

### ISSUE THREAD

**Issue by markiewb** [mcheung63/MavenRunner#6]
![2016-02-13_11h02_59](https://cloud.githubusercontent.com/assets/1857095/13027138/be4a6be8-d243-11e5-91c2-0d66adbe8cbc.png)

It doesn't look good on dark themes

**Comment by mcheung63** [comment]
i was using these:

//		if (selected) {
//			setBackground(UIManager.getColor("Tree.selectionBackground"));
//			setForeground(UIManager.getColor("Tree.selectionForeground"));
//		} else {
//			setBackground(UIManager.getColor("Tree.background"));
//			setForeground(UIManager.getColor("Tree.foreground"));
//		}

but it doesn't work in some netbeans built-in themes, so i am using this now:
		if (selected) {
			setBackground(new Color(9, 80, 208));
			setForeground(Color.white);
		} else {
			setBackground(Color.white);
			setForeground(Color.black);
		}

Let me find a better way to handle this, thanks :)

**Comment by markiewb** [comment]
![2016-02-13_12h01_59](https://cloud.githubusercontent.com/assets/1857095/13027406/5b244cd0-d24f-11e5-8287-2cf0edc800a7.png)


```
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.peter.mavenrunner;

import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JTree;
import javax.swing.UIManager;
import javax.swing.tree.TreeCellRenderer;
import org.netbeans.api.project.ProjectInformation;

/**
 *
 * @author peter
 */
public class MyTreeNodeRenderer extends JLabel implements TreeCellRenderer {

        public MyTreeNodeRenderer() {
            //HACK: set opaque to use Tree.selectionBackground/Tree.textBackground
            setOpaque(true);
        }

    
	@Override
	public Component getTreeCellRendererComponent(JTree tree, Object value, boolean selected, boolean expanded, boolean leaf, int row, boolean hasFocus) {
		MyTreeNode treeNode = (MyTreeNode) value;
		if (treeNode.type != null && treeNode.type.equals("project")) {
			ProjectInformation pi = treeNode.projectInformation;
			setText(pi.getDisplayName());
		} else {
			setText(treeNode.name);
		}
		setIcon(treeNode.icon);
		if (selected) {
			setBackground(UIManager.getColor("Tree.selectionBackground"));
			setForeground(UIManager.getColor("Tree.selectionForeground"));
		} else {
			setBackground(UIManager.getColor("Tree.textBackground"));
			setForeground(UIManager.getColor("Tree.textForeground"));
		}
		return this;
	}
}

```

**Comment by mcheung63** [comment]
i figured it out, nimbus use this:

setBackground(UIManager.getColor("nimbusSelectionBackground"));

:-)

**Comment by mcheung63** [comment]
Fixed, at least it works in all laf, including "Dark Metal" theme

[https://www.dropbox.com/s/4efv2vqq6prkumd/support%20dark%20theme.png?dl=1]
