### ISSUE TITLE
Code uses obsolete java.util.Hashtable/java.util.Vector

### ISSUE THREAD

**Issue by markiewb** [mcheung63/MavenRunner#7]
Use HashMap and ArrayList instead

**Comment by mcheung63** [comment]
Fixed, deploy soon. Don't know why java.util.Vector is obsolete, it has some advantage if compare to arraylist.

**Comment by markiewb** [comment]
Vector is synchronized. The javadoc of Vector says 
```
If a thread-safe implementation is not needed, it is recommended to use {@link ArrayList} in place of {@code Vector}.
```

You can create a synchronized collection using ```Collections.synchronizedList(myListInstance)``` if needed.

**Comment by mcheung63** [comment]
Fixed, thanks
